export const mainRed = "rgb(11,70,184)"
export const mainDark = "#333333"
export const lightGrey = '#f1f1f1';
export const fontSize = '15px'
export const fontSize2 = '20px'
export const fontSizeBig2 = '45px'
export const fontSizeBig = '56px'
export const fontSizeMedium = '30px';
export const fontFamily2 = "'Ruda', sans-serif;";
export const fontSizeM = "16px";
export const fontSizeMediumM = "20px";
export const fontSizeBigM = "22px";